/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AidesEtTarifsRouteImport } from './routes/aides-et-tarifs'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrestationsRouteImport } from './routes/prestations'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as ZoneInterventionRouteImport } from './routes/zone-intervention'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AidesEtTarifsRoute = AidesEtTarifsRouteImport.update({
  id: '/aides-et-tarifs',
  path: '/aides-et-tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestationsRoute = PrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const ZoneInterventionRoute = ZoneInterventionRouteImport.update({
  id: '/zone-intervention',
  path: '/zone-intervention',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aides-et-tarifs': typeof AidesEtTarifsRoute
  '/faq': typeof FaqRoute
  '/prestations': typeof PrestationsRoute
  '/temoignages': typeof TemoignagesRoute
  '/zone-intervention': typeof ZoneInterventionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aides-et-tarifs': typeof AidesEtTarifsRoute
  '/faq': typeof FaqRoute
  '/prestations': typeof PrestationsRoute
  '/temoignages': typeof TemoignagesRoute
  '/zone-intervention': typeof ZoneInterventionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/aides-et-tarifs': typeof AidesEtTarifsRoute
  '/faq': typeof FaqRoute
  '/prestations': typeof PrestationsRoute
  '/temoignages': typeof TemoignagesRoute
  '/zone-intervention': typeof ZoneInterventionRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/aides-et-tarifs'
    | '/faq'
    | '/prestations'
    | '/temoignages'
    | '/zone-intervention'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/aides-et-tarifs'
    | '/faq'
    | '/prestations'
    | '/temoignages'
    | '/zone-intervention'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/aides-et-tarifs'
    | '/faq'
    | '/prestations'
    | '/temoignages'
    | '/zone-intervention'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AidesEtTarifsRoute: typeof AidesEtTarifsRoute
  FaqRoute: typeof FaqRoute
  PrestationsRoute: typeof PrestationsRoute
  TemoignagesRoute: typeof TemoignagesRoute
  ZoneInterventionRoute: typeof ZoneInterventionRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aides-et-tarifs': {
      id: '/aides-et-tarifs'
      path: '/aides-et-tarifs'
      fullPath: '/aides-et-tarifs'
      preLoaderRoute: typeof AidesEtTarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestations': {
      id: '/prestations'
      path: '/prestations'
      fullPath: '/prestations'
      preLoaderRoute: typeof PrestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zone-intervention': {
      id: '/zone-intervention'
      path: '/zone-intervention'
      fullPath: '/zone-intervention'
      preLoaderRoute: typeof ZoneInterventionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AidesEtTarifsRoute: AidesEtTarifsRoute,
  FaqRoute: FaqRoute,
  PrestationsRoute: PrestationsRoute,
  TemoignagesRoute: TemoignagesRoute,
  ZoneInterventionRoute: ZoneInterventionRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
